version: "3.7"
services:
  dawarich:
    image: freikin/dawarich:0.26.0
    container_name: dawarich
    entrypoint: web-entrypoint.sh
    command:
      ["bin/rails", "server", "-p", "3000", "-b", "::"]
    stdin_open: true
    tty: true
    environment:
      - TZ=${TZ}
      - RAILS_ENV=development
      - REDIS_URL=redis://dawarich-redis:6379/0
      - DATABASE_HOST=dawarich-db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=dawarich_development
      - MIN_MINUTES_SPENT_IN_CITY=10
      - APPLICATION_HOSTS=localhost,dawarich.murkmesc.top
      - TIME_ZONE=${TZ}
      - APPLICATION_PROTOCOL=http
      - DISTANCE_UNIT=km
      - PROMETHEUS_EXPORTER_ENABLED=false
      - PROMETHEUS_EXPORTER_HOST=0.0.0.0
      - PROMETHEUS_EXPORTER_PORT=9394
      - SELF_HOSTED=true
    volumes:
      - ${APP_DATA_DIR}/data/public:/var/app/public
      - ${APP_DATA_DIR}/data/imports/watched:/var/app/tmp/imports/watched
      - ${APP_DATA_DIR}/data/storage:/var/app/storage
    dns:
      - ${DNS_IP}
    ports:
      - ${APP_PORT}:3000
    restart: unless-stopped
    depends_on:
      - dawarich-db
      - dawarich-redis
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.dawarich-web-redirect.redirectscheme.scheme: https
      traefik.http.services.dawarich.loadbalancer.server.port: 3000
      # Web
      traefik.http.routers.dawarich-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.dawarich-insecure.entrypoints: web
      traefik.http.routers.dawarich-insecure.service: dawarich
      traefik.http.routers.dawarich-insecure.middlewares: dawarich-web-redirect
      # Websecure
      traefik.http.routers.dawarich.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.dawarich.entrypoints: websecure
      traefik.http.routers.dawarich.service: dawarich
      traefik.http.routers.dawarich.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.dawarich-local-insecure.rule: Host(`dawarich.${LOCAL_DOMAIN}`)
      traefik.http.routers.dawarich-local-insecure.entrypoints: web
      traefik.http.routers.dawarich-local-insecure.service: dawarich
      traefik.http.routers.dawarich-local-insecure.middlewares: dawarich-web-redirect
      # Local domain secure
      traefik.http.routers.dawarich-local.rule: Host(`dawarich.${LOCAL_DOMAIN}`)
      traefik.http.routers.dawarich-local.entrypoints: websecure
      traefik.http.routers.dawarich-local.service: dawarich
      traefik.http.routers.dawarich-local.tls: true
      runtipi.managed: true
  dawarich-db:
    image: postgis/postgis:17-3.5-alpine
    container_name: dawarich-db
    environment:
      - TZ=${TZ}
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
      - ${APP_DATA_DIR}/data/shared:/var/shared
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
  dawarich-redis:
    image: redis:7.0-alpine
    container_name: dawarich-redis
    environment:
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/data/shared:/data
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
  dawarich-sidekiq:
    image: freikin/dawarich:0.26.0
    container_name: dawarich-sidekiq
    entrypoint: sidekiq-entrypoint.sh
    command: ["sidekiq"]
    stdin_open: true
    tty: true
    environment:
      - TZ=${TZ}
      - RAILS_ENV=development
      - REDIS_URL=redis://dawarich-redis:6379/0
      - DATABASE_HOST=dawarich-db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=dawarich_development
      - APPLICATION_HOSTS=localhost,dawarich.murkmesc.top
      - BACKGROUND_PROCESSING_CONCURRENCY=10
      - TIME_ZONE=${TZ}
      - APPLICATION_PROTOCOL=http
      - DISTANCE_UNIT=km
      - PROMETHEUS_EXPORTER_ENABLED=false
      - PROMETHEUS_EXPORTER_HOST=0.0.0.0
      - PROMETHEUS_EXPORTER_PORT=9394
      - SELF_HOSTED=true
    volumes:
      - ${APP_DATA_DIR}/data/public:/var/app/public
      - ${APP_DATA_DIR}/data/imports/watched:/var/app/tmp/imports/watched
      - ${APP_DATA_DIR}/data/storage:/var/app/storage
    dns:
      - ${DNS_IP}
    restart: unless-stopped
    depends_on:
      - dawarich
      - dawarich-db
      - dawarich-redis
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
